[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
sqlx = { version = "0.8.1", features = ["postgres", "runtime-tokio"] }
tokio = { version = "1.39.3", features = ["full", "macros"] }
tower-cookies = "0.10.0"
tower-http = { version = "0.5.2", features = ["cors", "fs"] }
